drop table if exists books;

-- Table used by the REST CRUD demo.
create table books (
    id bigint generated by default as identity primary key,
    title varchar(120) not null,
    author varchar(120) not null,
    price decimal(10, 2) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);
